### ISSUE TITLE
Manifest errors

### ISSUE THREAD

**Issue by N6REJ** [RickR2H/joomla-issue-tracker-switcher#1]
Received the following errors on activation...
![image](https://user-images.githubusercontent.com/1850089/180643861-6222a5a3-c1a5-4730-9ee9-1fe546c907d8.png)

![image](https://user-images.githubusercontent.com/1850089/180643848-ffc6fcaf-3106-4e6e-bd8b-580a91f0b287.png)

```
{
    "manifest_version": 2,

    "name": "Joomla Issue Switcher",
    "description": "Switch between the current Joomla issue and the Github issue tracker",
    "version": "1.0.0",
    "icons": {
        "16": "icon_16.png",
        "48": "icon_48.png",
        "128": "icon_128.png"
    },
    "browser_action": {
        "default_icon": "icon.png",
        "default_popup": "popup.html"
    },
    "permissions": [
        "activeTab"
    ]
}
```

**Comment by RickR2H** [comment]
Manifest updates. Please check new version and install via Github and report back. If everything is okay, I'll post it to the store.

**Comment by N6REJ** [comment]
errors are gone
