### ISSUE TITLE
Toggle doesn't function

### ISSUE THREAD

**Issue by N6REJ** [RickR2H/joomla-issue-tracker-switcher#3]
When I am on either git or jissues and hit "toggle" nothing happens but a flash

**Comment by RickR2H** [comment]
Did you open an issue and then try to switch? The button only works is you have an issue open on git or issue tracker.

**Comment by N6REJ** [comment]
no, i can give that a try.

**Comment by N6REJ** [comment]
yep, that works.. ty.
